### ISSUE TITLE
Return multiple function arguments in quote block expression

### ISSUE THREAD

**Issue by 0----0** [zdevito/terra#111]
Using backticks, it's possible to return multiple expressions in a way that works both for destructuring and argument passing, shown below.
```lua
local std = terralib.includec("stdio.h")

expr = macro(function()
        local exprs = terralib.newlist {`1, `2}
        return `exprs
end)

local terra twoargs(x: int, y: int)
        std.printf("%d %d\n", x, y)
end
        
local terra test()
        var x, y = expr()
        twoargs(expr())
end
test()
```
However, if you use `quote` expressions, you get different behavior.
```lua
local std = terralib.includec("stdio.h")

expr = macro(function()
        local exprs = terralib.newlist {`1, `2}
        return quote in exprs end
end)

local terra twoargs(x: int, y: int)
        std.printf("%d %d\n", x, y)
end
        
local terra test()
        var x, y = expr()
        twoargs(expr())
end
test()
```
Instead of returning two things, the quote expression returns a single tuple.  As a result, `var x, y = expr()` works, but `twoargs(expr())` does not.

Even though it may be bad programming practice, I've found returning multiple function arguments to be a useful feature, emulating lua unpacking.  However, I need to use quote-block expressions for optimization, preventing an input expression from getting duplicated if I return it multiple times.  There doesn't seem to be any way to do that, short of manually constructing AST entries.

**Comment by zdevito** [comment]
I originally did use this behavior where functions and `quote in end` could return multiple values and it could be threaded through to functions. It turns out, though, that it interacts in a very complicated way with macros.  In particular you might have something like

    local myquote = quote
          var a = function_with_side_effects()
    in
          a, a + 1
    end
    terra thing()   
        foo(myquote)
    end

If `foo` is a function, then it is clear how to pass both arguments to it.  If `foo` is a macro we also need to pass 2 arguments to it, otherwise replacing a function with a macro causes inconsistent argument passing behavior. However, a macro is allowed to not execute its arguments, or execute them more than once, or put them in a conditional, etc. If the first and second component of myquote are passed separately and executed in different conditionals, when should `function_with_side_effects()` execute? 
Since this is not well-define, terra just includes simple rules for taking tuples and splitting them up rather than Lua's multiple argument system. If you want more generic behavior for splitting up a tuple you could write:

    local terra test()
         var t = expr()
         twoargs(unpacktuple(t))
    end
