### ISSUE TITLE
Question about saveobj

### ISSUE THREAD

**Issue by rokf** [zdevito/terra#168]
I have a module `mod.lua` for example:
```
local M = {}
M.tmp = 123
return M
```
and this:
```
local mod = require 'mod'
terra main()
  C.printf("%d", mod.tmp)
end
```

There's currently no way to read a value from a module dynamically if run from a executable produced by `terralib.saveobj` right?

I know that this will work if I change the `M.tmp` value and run it with `terra filename.t`

I've read that it does not work for functions, how about  variables? What I'd like to achieve is some sort of simple scripting capability (compiled executable reading values from `mod.lua` at startup). Not possible yet, am I right?

**Comment by zdevito** [comment]
Sorry -- I just missed this question from a few days ago. It is a good question though. Currently saveobj does not attempt to save any of the Lua state of the program, which includes Lua functions or any other values. It's actually really hard to do that in an automated way because many Lua functions or value indirectly reference the entire state of Lua and saving/restoring that state is not easy. It is also probably not what someone intends when referencing a function either.
