### ISSUE TITLE
Defining a variadic terra function

### ISSUE THREAD

**Issue by brandonbloom** [zdevito/terra#169]
Is it currently possible? I don't see any examples of it in the test suite. Searching for `varargs` suggests the implementation of this might be incomplete.

While `terra(...) end` seems to compile, `terra(x, ...) end` does not. There also doesn't seem to be any obvious way to use `...` from the body of the function.

Use case: I'd like to define a helper function that delegates to printf.

As a workaround, I'm using a variadic macro.

**Comment by zdevito** [comment]
It's currently not possible. Some of the infrastructure for it is
implemented in the parser, as you saw, but it hasn't been plumbed through
the compiler. This is  because a lot vararg things are easier to write as
variadic macros, so I haven't gotten around to it.  However, it can be
useful for compatibility with C.
