### ISSUE TITLE
old LLVM?

### ISSUE THREAD

**Issue by andrewrk** [zdevito/terra#198]
Hey, just curious is there a technical reason why terra is stuck on 3.5? That version is 2 years old at this point, with 3.8 being the latest and 3.9 release date 1 month from now.

Package managers are starting to want to drop older LLVM versions (see https://github.com/NixOS/nixpkgs/issues/15974), so it might be nice to get up to speed.

Cool project BTW. Hello from the author of [Zig](http://ziglang.org/). We have some similar ideas here.

**Comment by 0joshuaolson1** [comment]
Hi Andrew. About what's involved:

https://github.com/zdevito/terra/issues/125

Also, some counterpoints. While I too would love to see 3.9 support, building Terra already requires building LLVM afaik. Its C++ API also changes more than its minimal C API according to [llvmlite](https://github.com/numba/llvmlite). I'm not sure if the Khronos group, for example, still standardizes around particular LLVM releases.

**Comment by andrewrk** [comment]
Ah thanks for the link to the other issue, didn't see that.

**Comment by zdevito** [comment]
Just to follow up, Terra does build and work against llvm 3.8 and
everything works except for some debug information. The major reason for
keeping it at llvm 3.5 in the releases for now is to support CUDA
programming because the current release of CUDA compiler uses an old
version of LLVM. Once CUDA 8.0 is release, we can bump the official LLVM
version up to 3.8.

-- Zach

**Comment by andrewrk** [comment]
Thanks for the explanation, @zdevito. That makes sense.
