### ISSUE TITLE
Does saveobj optimize like -O3?

### ISSUE THREAD

**Issue by 0joshuaolson1** [zdevito/terra#227]
It's not clear. On a related note, does saveobj do additional LLVM passes over JITting?

This discussion (one post as of Jan. 2017): https://mailman.stanford.edu/pipermail/terralang/2016-December/000568.html

**Comment by elliottslaughter** [comment]
Yes, it's `-O3`:

https://github.com/zdevito/terra/blob/master/src/tllvmutil.cpp#L368

(called from: https://github.com/zdevito/terra/blob/master/src/tcompiler.cpp#L2890)

There is now an optional parameter to `saveobj` to turn off optimizations completely. Otherwise this aspect of Terra isn't very configurable at the moment.
