### ISSUE TITLE
CUDA not enabled when using release version

### ISSUE THREAD

**Issue by mxgbs** [zdevito/terra#253]
Hi,

My platform is windows 10, 64bits, VS2015. When I tried to use terra to execute cuda related code, following error occurs. Can someone help with me with this problem?
\Optlang\terra\bin>terra ..\share\terra\tests\cudahello.t
CUDA not enabled, not performing test...

Sincerely,

Yan

**Comment by elliottslaughter** [comment]
This has been fixed in the new build under `msvc/Makefile`. You need to set `CUDA_DIR` in the environment to the location of the CUDA installation, and rebuild Terra.

Just FYI, there are also new binaries for Windows in the beta release, and they include CUDA. See them here: #323

I'm closing this issue for now but please feel free to let us know if you find any other issues.
