### ISSUE TITLE
How to typecast strings?

### ISSUE THREAD

**Issue by tomas** [zdevito/terra#291]
This is probably a noob question, but I'm unable to run a very simple test:

```
c = terralib.includec("stdio.h")

function foo()
  return "foo"
end

test = terralib.cast({}->{rawstring}, foo)

terra hello()
  c.printf("hello, %s!\n", test())
end

hello()
```

This gives a `cannot convert 'string' to 'char *'` error. I tried using `&int8` as the type with the same result. What am I doing wrong?

And thanks!

**Comment by elliottslaughter** [comment]
Actually it's a good question. This is a little convoluted in Terra. The root of the problem is that LuaJIT's FFI (which Terra builds on) wants to convert a Lua string to a `const char *` instead of a `char *` (i.e. it wants it to be immutable). But Terra's type system doesn't have any notion of `const`, so don't think there's even a way to write that type.

You can get around it, but basically you end up needing to build the value yourself in Lua before returning it. You can use `terralib.constant` to wrap the string, but as far as I know the only publicly exposed way to return the cdata value for that is by wrapping it in a Terra function. So something like this should do the trick:

```
c = terralib.includec("stdio.h")

function foo()
  local x = terralib.constant(rawstring, "foo")
  return (terra() return x end)()
end

test = terralib.cast({}->{rawstring}, foo)

terra hello()
  var s : rawstring = test()
  c.printf("hello, %s!\n", s)
end
hello()
```

Hope that helps.

**Comment by tomas** [comment]
I see. Thanks @elliottslaughter !
