### ISSUE TITLE
Results of Lua and Terra differ for the same simple test

### ISSUE THREAD

**Issue by bel2125** [zdevito/terra#301]
I just discovered terra on a scripting [language comparison page](https://github.com/r-lyeh-archived/scriptorium/blob/master/README.md), so I decided to give it a try, downloaded the latest binary (release-2016-03-25: terra-Windows-x86_64-332a506.zip) and wrote a simple test script:

```Lua
function f_lua(cnt)
  local j = 0.0
  for i=1,cnt do j = j + i end
  return j
end

terra f_ter(cnt : double) : double
  var j : double = 0.0
  var i : int64 -- not just int - will overflow at 2^31 ~ 2.15*10^9
  var icnt : int64 = cnt
  for i=1,icnt do j = j + i end
  return j
end
```

However, the result is somewhat surprising.
First of all, the results from Lua and Terra are different:

```Lua
for n=0,10 do
  print(n, f_lua(n), f_ter(n))
end
```
| n | f_lua | f_ter |
| -- | -- | -- |
|0|0|0|
|1|1|0|
|2|3|1|
|3|6|3|
|4|10|6|
|5|15|10|
|6|21|15|
|7|28|21|
|8|36|28|
|9|45|36|
|10|55|45|
 
Second, the speed advantage of a factor of 11 over plain Lua (according to [this page](https://github.com/r-lyeh-archived/scriptorium/blob/master/README.md)), but it's rather ~ 20% (not 1000%)

```Lua
for n=0,11 do
  local z = 10^n
  local t1 = os.time()
  local r_lua = f_lua(z)
  local t2 = os.time()
  local r_ter = f_ter(z)
  local t3 = os.time()
  print(z, r_lua, t2-t1, r_ter, t3-t2)
end
```
| n | f_lua | t_lua| f_ter | t_ter |
| -- | -- | -- |-- | -- |
1    |   1   |    0    |   0   |    0
10    |  55     | 0      | 45    |  0
100 |    5050  |  0     |  4950  |  0
1000  |  500500 | 0   |    499500 | 0
10000 |  50005000    |    0   |    49995000       | 0
100000 | 5000050000   |   0   |    4999950000   |   0
1000000| 500000500000   | 0    |   499999500000  |  0
10000000     |   50000005000000|  0    |   49999995000000|  0
100000000   |    5.00000005e+015 |0    |   4.99999995e+015| 0
1000000000  |    5.0000000006711e+017  |  2   |    4.9999999906711e+017 |   1
10000000000   |  5.0000000000068e+019 |   16    |  4.9999999990068e+019  |  13
100000000000  |  4.999999999898e+021  |   160    | 4.999999999798e+021   |  132 

Did I use something wrong, or is this a bug?

**Comment by elliottslaughter** [comment]
So the answer to your first question is that Terra uses exclusive iteration, where as Lua uses inclusive. That is, `for i = 0, N` goes from `0` to `N-1` in Terra, instead of `0` to `N` in Lua. That means you have to add 1 to the upper loop bound to make them equivalent. The program at the bottom of this comment should get the same results for Lua and Terra.

(Note: while Lua loops can technically start a 0, they almost always start at 1. So the idiomatic way to write the loop in Terra would be `for i = 0, N` (which iterates from `0` to `N-1`), whereas in Lua you'd normally write `for i = 1, N` (which iterates from `1` to `N`). Also note that Lua arrays start at 1 while Terra arrays start at 0, so this is what you have to do if you want to iterate an array with `N` elements.)

As for the (lack of) performance difference, keep in mind that the Lua used by Terra is **LuaJIT**, not plain Lua. LuaJIT is an optimizing JIT compiler for Lua that is very well respected, it's basically one of the best dynamic language JITs out there, probably only surpassed by JavaScript (if that).

If you go to the page you linked, the difference between LuaJIT and Terra is around what you reported (~20%). The difference between PUC Lua (the original Lua interpreter) and Terra is 10x. This is inline with what I'd expect.

Given this you might be wondering what the advantages of Terra would be over LuaJIT. There are a number of them:

  * LuaJIT relies entirely on the magic of JIT to make your code fast. If it works, it's great. But if it doesn't, you're stuck writing your code in C (or Terra). Terra gives much more predictable performance.
  * Terra can do basically anything C can do. This includes features for performance. E.g. you can write manually vectorized code. So you can depend on Terra always giving you performance that is at least as good as C. JIT can sometimes do this, but it's not reliable, and it depends very strongly on the kind of code you're running.
  * Terra makes it very easy to interface with C. You can directly import C header files. In LuaJIT you have to transliterate those header files into the subset of C that LuaJIT undertands.
  * Terra doesn't use a VM, unlike LuaJIT (and other JIT languages like Java). There are lots of things that this makes easier, especially when dealing with C. Also, tools like valgrind just work, whereas they almost never work with VM-based languages.
  * As a JIT, LuaJIT relies heavily on a GC to manage memory. Terra is like C, so it will never allocate memory except when you say so. Small, fixed size values like structs and arrays can be passed on the stack without any use of heap allocation at all.
  * JITs are known for having potentially bad startup time. Terra can produce binaries that do not depend on LuaJIT (or Terra), just like if you were compiling straight C code. These run with literally no startup overhead.

```
function f_lua(cnt)
  local j = 0.0
  for i=1,cnt do j = j + i end
  return j
end

terra f_ter(cnt : double) : double
  var j : double = 0.0
  var i : int64 -- not just int - will overflow at 2^31 ~ 2.15*10^9
  var icnt : int64 = cnt + 1
  for i=1,icnt do j = j + i end
  return j
end

for n=0,10 do
  print(n, f_lua(n), f_ter(n))
end

local c = terralib.includec("time.h")
terra get_time()
  var t : c.timespec
  c.clock_gettime(c.CLOCK_MONOTONIC, &t)
  return double(t.tv_sec*1e9 + t.tv_nsec)/1e9
end

for n=0,11 do
  local z = 10^n
  local t1 = get_time()
  local r_lua = f_lua(z)
  local t2 = get_time()
  local r_ter = f_ter(z)
  local t3 = get_time()
  print(z, t2-t1, t3-t2)
end
```

**Comment by elliottslaughter** [comment]
By the way, in the code above I used some C header files to use a high resolution clock. This is an example of how easy it is to use C in Terra. It pretty much doesn't get any easier than this, in any language.

**Comment by elliottslaughter** [comment]
A point I forgot: Terra can be used to generate code for GPUs. I don't think this is something that is ever going to happen with JITs like LuaJIT. The best they might do would provide a way to call CUDA, or maybe they could add a (very small) subset of the language that they could compile automatically. But the level of integration that Terra has with GPUs is simply impossible with modern compiler technology (regardless of whether it's JIT or not).

**Comment by bel2125** [comment]
Thanks for your detailed explanation.
Now I understand the results of the test code.

I changed the Terra code to add 1 to count and did a performance test with plain Lua (not with LuaJit used by the Terra executable) and found a performance factor of 6. So, my new test results are in accordance with your explanation.
