### ISSUE TITLE
Binary builds of development versions

### ISSUE THREAD

**Issue by aiverson** [zdevito/terra#318]
Would it be possible to have the CI builds store the binaries produced somewhere so that there is a downloadable "release" of the latest development version? That way there is a binary version with all the latest features available without needing to compile it on the system. That would make it much easier to download and use terra projects which depend on new features or get up and running on development with the current version of terra.

**Comment by elliottslaughter** [comment]
@aiverson There are binaries of the beta version here: https://github.com/zdevito/terra/releases/tag/release-1.0.0-beta1

(Note: Linux and Mac are still in progress but should be up soon.)

Since the release infrastructure is now fully automated, it should be easy to make releases more frequently, so hopefully stale binaries won't be an issue in the future.

**Comment by aiverson** [comment]
Awesome! I will start using these.

**Comment by elliottslaughter** [comment]
I'm going to close this for now, but please feel free to comment or open a new issue if there is anything else.
