### ISSUE TITLE
Unable to use union / unnamed struct in terra

### ISSUE THREAD

**Issue by paniq** [zdevito/terra#76]
I attempted to translate a bunch of C struct definitions to terra, but there seems to be no equivalent in the language to specify unnamed structs within a top level union. An example declaration that fails is

```
typedef union vec3 {
    float i[3];
    struct {
        float x;
        float y;
        float z;
    };
} vec3_t;
```

How would I go about porting this to terra? I would have used terralib.includestring, but for structs generated in this way attributes seem to be missing when an unnamed struct is used, and I get a weird error when trying to use these structs as types in terra functions:

```
terra: src/tcompiler.cpp:720: llvm::Type *CCallingConv::TypeForClass(size_t, CCallingConv::RegisterClass): Assertion `!"unexpected class"' failed.
```

**Comment by paniq** [comment]
any news on this?

**Comment by zdevito** [comment]
I looked into this awhile ago, but it looks like I never commented here. Terra doesn't have the concept of an unnamed struct itself. The intension is that in Terra you can get the behavior you want using meta-programming of the .x, .y, and .z property selectors. 

As for translating C structs that already do this, would it be helpful if it imported them but gave a name to them when they appeared (e.g. it would be v._0.x)? With that it would be possible for you to attach a __entrymissing metamethod so that writing v.x would still work.

**Comment by zdevito** [comment]
I changed how we translate C structs to automatically assign names (_0,_1,...) to anonymous structs and unions inside other structs. The test tests/canon2.t shows how to write an `__entrymissing` metamethod to generically proxy selections  to the anonymous struct (e.g. `v.x` becomes `v._0.x`).
