### ISSUE TITLE
Global not replaced when redeclaring terra function

### ISSUE THREAD

**Issue by Starcounter-Jack** [zdevito/terra#85]
If I run this from the REPL, I get 123 as the result.

``` terra
terra hello()
    return 123
end
terra hello()
   return 456
end
print(hello())
```

When I run the following in Lua, I get 456

``` lua
function hello()
   return 123
end
function hello()
   return 456
end
print(hello())
```

The Lua semantics make sense as I'm really assigning the second lambda to the same global whereas the Terra appear to have a bug.

In Terra, am I generating two LLVM functions? Why is not hello assigned to the second function?

**Comment by zdevito** [comment]
Terra has the concept of overloaded functions, so when you define hello
twice, you are giving the function hello two definitions (the syntax sugar
is basically equivalent to:

hello = (hello or newterradeclaration()):adddefinition(<functionbody>)

 If you were to try to call it from Terra, you would get an error reporting
the overloaded function is ambiguous:

> terra hello() return 1 end terra hello() return 2 end terra use() hello()
end

> use()

src/terralib.lua:545: Errors reported during compilation.

[string "stdin"]:1: call to overloaded function is ambiguous. can apply to
type list () type list ()

Calling overloaded functions from Lua is not implemented in the best way
right now, since I have no way of query whether LuaJIT will report an error
coercing the arguments, so it just tries to call the first one. In the
future, this may change to make this behavior more obvious.

**Comment by Asmageddon** [comment]
I think that there should be a warning when you introduce multiple identical overloads, and that in said case, the latest version should be chosen, in accordance with how Lua works. As for multiple dispatch, for starters, why not implement a naive type-checking dispatcher? Sounds better than nothing, IMO.

**Comment by Qix-** [comment]
This issue should be closed as Terra now errors upon duplicate `terra` function declarations.

```terra
local io = terralib.includec('stdio.h')

terra hello()
	return 10
end

terra hello(x: int)
	return 10 + x
end

terra main()
	io.printf("%d\n%d\n", hello(), hello(10))
end

main()
```

yields:

```
testol.t:3: Errors reported during function declaration.
testol.t:7: duplicate definition of function
terra hello(x: int)
           ^
testol.t:3: previous definition is here
terra hello()
           ^

stack traceback:
	[C]: in function 'error'
	src/terralib.lua:388: in function 'finishandabortiferrors'
	src/terralib.lua:1086: in function 'defineobjects'
	testol.t:3: in main chunk
```

**Comment by elliottslaughter** [comment]
Thanks for pointing this out!
